name: Build and Release

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all history for changelog generation
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Get version from pom.xml
      id: get_version
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        TIMESTAMP=$(date +%Y%m%d%H%M%S)
        CLEAN_VERSION=${VERSION//-SNAPSHOT/}
        RELEASE_VERSION="${CLEAN_VERSION}-${TIMESTAMP}"
        echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV
    
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    
    - name: Generate changelog
      run: .github/scripts/generate_changelog.sh
    
    - name: Update version in pom files
      run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} -DgenerateBackupPoms=false
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        name: Release ${{ env.RELEASE_VERSION }}
        tag_name: v${{ env.RELEASE_VERSION }}
        body_path: changelog.md
        draft: false
        prerelease: false
        files: |
          mcp-server/target/mcp-server-*-fat.jar
          agent/target/agent-*-fat.jar
          tools/target/tools-*.jar
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: k8s-ai-artifacts
        path: |
          mcp-server/target/mcp-server-*-fat.jar
          agent/target/agent-*-fat.jar
          tools/target/tools-*.jar
